general {
    # Comando para travar a tela - evita múltiplas instâncias do hyprlock
    lock_cmd = pidof hyprlock || hyprlock
    # Trava a tela antes de suspender (ao fechar o lid)
    before_sleep_cmd = loginctl lock-session
    # Reativa a tela ao voltar do suspend sem precisar apertar tecla duas vezes
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 150                          # 2.5min sem input
    on-timeout = brightnessctl -s set 10   # reduz brilho ao mínimo (salva o valor atual)
    on-resume = brightnessctl -r           # restaura o brilho anterior
}

listener {
    timeout = 300                          # 5min sem input
    on-timeout = loginctl lock-session     # trava a tela
}

listener {
    timeout = 330                          # 5.5min - 30s após o lock
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'                   # desliga a tela
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r # religa e restaura brilho
}
